builders:
  artemis_bloc_gen:
    import: "package:artemis_bloc_gen/artemis_bloc_gen.dart"
    builder_factories: ["artemisBlocBuilder"]
    # The `partId` argument to `SharedPartBuilder` is "some_cool_builder"
    build_extensions: {".dart": [".info.dart"]}
    auto_apply: dependents
    build_to: cache
    # To copy the `.g.part` content into `.g.dart` in the source tree
    applies_builders: ["source_gen|combining_builder", 'artemis']