builders:
  gqlBlogBuilder:
    import: "package:gql_bloc_gen/gql_bloc_gen.dart"
    builder_factories: ["gqlBlogBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder", "artemis"]