builders:
  artemisBlocBuilder:
    import: "package:artmis_bloc_gen/artemis_bloc_gen.dart"
    builder_factories: ["artemisBlocBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder", "artemis"]