name: artemis_bloc_gen
description: Generate bloc for artimis generated classes
version: 1.0.2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  analyzer:
  build:
  flutter:
    sdk: flutter
  source_gen:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
#flutter:
#  assets:
#    - assets/templates/template_bloc.dart.temp
